---
- name: "Check if host is registered to RHN"
  ansible.builtin.shell: subscription-manager status| awk '/Overall Status:/{print $3}'
  register: subscription_status
  changed_when: false

- name: "Check if repositories are enabled already"
  ansible.builtin.shell: "subscription-manager repos --list-enabled| awk '/Enabled:   1/ {count ++} END {print count}'"
  register: repositories_status
  changed_when: false

- name: import secret variable file
  include_vars: "vars/vault.yml"
  no_log: true

- name: "register System with RHN Subscription Manager"
  community.general.redhat_subscription:
    server_hostname: "{{ satellite_hostname | default(omit) }}"
    server_insecure: "{{ satellite_insecure | default(omit) }}"
    state: present
    username: "{{ rhn_user | default(satellite_username) | default(omit) }}"
    password: "{{ rhn_pwd | default(satellite_password) | default(omit) }}"
    force_register: "{{ register_rhn | bool }}"
    # pool_ids: "{{ [rhn_pool_name] | default([]) }}"
  when: ansible_distribution == 'RedHat' and register_rhn and subscription_status != 'Current'

- name: "Disable all repositories"
  ansible.builtin.command: subscription-manager repos --disable=\*
  when: ansible_distribution == 'RedHat' and register_rhn and repositories_status.stdout <= "5"

- name: "Enable the needed rhel repositories"
  ansible.builtin.command: subscription-manager repos --enable={{ item }}
  with_items: "{{ rhel_repos }}"
  when: ansible_distribution == 'RedHat' and register_rhn and repositories_status.stdout <= "5"

- name: "Update packages"
  ansible.builtin.yum:
    name: '*'
    state: latest
  register: yum_result

- name: "Check if loaded kernel is the latest"
  ansible.builtin.shell: if [ $(uname -r) == $(rpm -q kernel | tail -n 1 | sed -e 's/kernel-//g') ] ; then echo no ; else echo reboot; fi
  ignore_errors: true
  register: reboot_hint

- name: "Make sure packages are not installed"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ packages_uninstall }}"

- name: "Make sure packages are installed"
  ansible.builtin.yum:
    name: "{{ packages_install }}"
    state: present

- name: "Reboot server, load new kernel"
  ansible.builtin.shell: sleep 2 && shutdown -r now "Ansible Restart Triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: yum_result.changed or reboot_hint.stdout.find("reboot") != -1

- name: "Waiting for server to come back"
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    delay: 10
    connect_timeout: 5
    timeout: 300
    port: 22
  delegate_to: 127.0.0.1
  become: false
  ignore_errors: true

- name: Refresh inventory to ensure new instaces exist in inventory
  ansible.builtin.meta: refresh_inventory
