---
- name: "Check the provided hosts are registered to the Satellite Server"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - when:
        - sat_register is defined
        - sat_register | bool
      block:
        - name: "Get the hosts from Satellite"
          ansible.builtin.uri:
            validate_certs: "{{ not (satellite_insecure | bool) }}"
            url: "https://read_hosts:lghKLRcuiPnIAK0WeTp8eA@{{ satellite_hostname }}/api/v2/hosts/{{ current_vm_item.value.fqdn }}"
            force_basic_auth: true
          loop: "{{ guests | dict2items }}"
          loop_control:
            loop_var: current_vm_item
...
