---
- hosts: pgoku
  gather_facts: yes
  become: yes
  become_method: sudo
  environment:
    LIBGUESTFS_BACKEND: direct
  vars:
    ssh_key_file: "/home/pgoku/.ssh/pgoku.key"
  roles:
    - role: kvm-guest-qcow2
      ### Variables
      ## Paths
      vm_location: "/var/lib/libvirt/images"
      image: "{{ os_image }}"
      path_output: "/var/log/cloud-init.log"
      inventory_file: "./inventory.yaml"
      ## Image 
      new_image_size: "{{ disk_size }}"
      ## Owner
      dir_owner: pgoku 
      dir_group: pgoku 
      useransible: pgoku
      ## Storage
      env_LIBGUESTFS_BACKEND: "direct"
      preallocation: metadata
      ssh_key: "{{ ssh_key_file + '.pub' }}"
      ## Users
      users:
        - name: pgoku
          groups: users,wheel
          shell: /bin/bash
          sudo: ALL=(ALL) NOPASSWD:ALL
      chg_pwd_users:
        - name: root
          password: redhat00
      ## Timezone
      timezone: "Europe/Madrid"
      ## VM definition
      guests: "{{ guest_list }}"
  post_tasks:
    - name: "Show variables for RHN or SAT registration"
      ansible.builtin.debug:
        var: "{{ current_var }}"
      loop:
        - skip_rhn_register
        - sat_register
      loop_control:
        loop_var: current_var

- ansible.builtin.import_playbook: rhn_register.yml
  when:
    - skip_rhn_register is not defined or not (skip_rhn_register | bool)
    - sat_register is not defined
