---
- name: "Prepare the list of the hosts to be registered to IDM"
  hosts: localhost
  connection: local
  tasks:
    - when: groups['rhn'] is not defined or groups['rhn'] | length == 0
      block:
        - name: "Create the dynamic inventory"
          ansible.builtin.add_host:
            hostname: "{{ current_guest_item.value.fqdn }}"
            groups: "rhn"
            ansible_ssh_user: "pgoku"
            ansible_ssh_private_key_file: "/home/pgoku/.ssh/pgoku.key"
            ansible_ssh_host: '{{ current_guest_item.value.address }}'
            # ansible_ssh_port: '{{ new_port }}'
          loop: "{{ guests | dict2items }}"
          loop_control:
            loop_var: current_guest_item

- name: "Change etc_resolv and enrolled to idm server"
  hosts: rhn
  gather_facts: yes
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: no
    main_domain: "bcnconsulting.com"
    ipa_user: 'admin'
    ipa_password: 'redhat00'
  roles:
    - role: "etc_resolv"
      resolv_nameservers:
        - "192.168.122.11"
      resolv_domain: "{{ main_domain }}"
      resolv_search:
        - "{{ main_domain }}"
      resolv_options:
        - "timeout:2"
        - "rotate"
  post_tasks:
    - name: "Make sure packages are installed"
      ansible.builtin.yum:
        name: "{{ packages_to_install }}"
        state: present
      vars:
        packages_to_install:
          - ipa-client

    - name: "Configure as ipa-client"
      ansible.builtin.command: >
              ipa-client-install -p {{ ipa_user }} --password '{{ ipa_password }}' --domain {{ main_domain }} --server idm.{{ main_domain }} --unattended --force-ntpd --enable-dns-updates
