---
- name: "Change etc_resolv and enrolled to idm server"
  hosts: rhn
  gather_facts: yes
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: no
  roles:
    - role: "etc_resolv"
      resolv_nameservers:
        - "192.168.122.13"
      resolv_domain: "lab.example.com"
      resolv_search:
        - "example.com"
        - "lab.example.com"
      resolv_options:
        - "timeout:2"
        - "rotate"
  post_tasks:
    - name: "Make sure packages are installed"
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - ipa-client

    - name: "Configure as ipa-client"
      command: >
              ipa-client-install -p admin --password 'redhat1234' --domain lab.example.com --server idm.lab.example.com --unattended --force-ntpd --enable-dns-updates
