---
- name: "Register the machines to the satellite server"
  hosts: satellite_clients
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: no
  roles:
    - role: sat-register
...
