---
- name: "Configure resolv.conf"
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    mode: "0644"
  become: True
- name: "Configure the nmcli connection"
  community.general.nmcli:
    conn_name: "System eth0"
    dns4: "{{ resolv_nameservers }}"
    dns4_search: "{{ resolv_domain }}"
    state: present
