---
controller_projects:
  - name: "Workflows Project"
    description: ""
    organization: "Satellite Register"
    scm_type: "git"
    scm_url: "git@github.com:automationiberia/Satellite-Register.git"
    scm_credential: "pgoku_github"
    scm_branch: "new_pgoku"
    scm_clean: "False"
    scm_delete_on_update: "False"
    scm_update_on_launch: "False"
    scm_update_cache_timeout: "0"
    allow_override: "False"
    timeout: 0
...
