---
controller_projects:
  - name: "Satellite Register - Project"
    description: ""
    organization: "Satellite Register"
    scm_type: "git"
    scm_url: "https://github.com/automationiberia/Satellite-Register.git"
    scm_credential: "Satellite Register - pgoku_github"
    #scm_branch: ""
    scm_clean: "False"
    scm_delete_on_update: "False"
    scm_update_on_launch: "False"
    scm_update_cache_timeout: "0"
    allow_override: "False"
    timeout: 0
...
