---
controller_credential_types:
  - name: "Satellite Register - Satellite Custom"
    description: ""
    kind: "cloud"
    inputs:
      fields:
      - id: hostname
        label: Satellite Register - Satellite Host
        secret: false
        type: string
      - id: insecure
        label: Satellite Register - Satellite Insecure
        type: boolean
      - id: organization
        label: Organization
        secret: false
        type: string
      - id: ak
        label: Activation Key
        secret: true
        type: string
      - id: location
        label: Location
        secret: false
        type: string
      - id: force
        label: Force registration
        type: boolean
      - id: username
        label: Username
        secret: true
        type: string
      - id: password
        label: Password
        secret: true
        type: string
      - id: update
        label: Update Packages
        type: boolean
      required:
      - hostname

    injectors:
      extra_vars:
        satellite_ak: !unsafe '{{ ak }}'
        satellite_force: !unsafe '{{ force }}'
        satellite_hostname: !unsafe '{{ hostname }}'
        satellite_insecure: !unsafe '{{ insecure }}'
        satellite_location: !unsafe '{{ location }}'
        satellite_organization: !unsafe '{{ organization }}'
        satellite_password: !unsafe '{{ password }}'
        satellite_update: !unsafe '{{ update }}'
        satellite_username: !unsafe '{{ username }}'
...
