---
controller_hosts:
  - name: "Satellite Register - pgoku.bcnconsulting.com"
    description: ""
    inventory: "Satellite Register - pgoku"
    variables:
      ansible_connection: ssh
      ansible_port: 42022
      ansible_ssh_host: 192.168.122.1
...
