---
controller_credentials:
  - name: "Satellite Register - Satellite Custom"
    description: ""
    credential_type: "Satellite Register - Satellite Custom"
    organization: "Satellite Register"
    inputs:
      ak: ''
      force: true
      hostname: satellite.bcnconsulting.com
      insecure: true
      location: pgoku
      organization: bcnconsulting
      update: false

...
