---
controller_credentials:
  - name: "Satellite Register - Vault"
    description: ""
    credential_type: "Vault"
    organization: "Satellite Register"
    inputs:
      vault_id: ''
      vault_password: 'redhat00'

...
