---
controller_credentials:
  - name: "pgoku"
    description: ""
    credential_type: "Machine"
    organization: "Satellite Register"
    inputs:
      become_method: sudo
      become_username: root
      username: pgoku
      ssh_key_data: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACANq8BOafs+Ix0yjUS50S46kL/Yv3QZLKIwv5yQ4SjSXAAAAJi8ZnfAvGZ3
        wAAAAAtzc2gtZWQyNTUxOQAAACANq8BOafs+Ix0yjUS50S46kL/Yv3QZLKIwv5yQ4SjSXA
        AAAEC/7bWJwKBehrhozyBJqENnLodvc3bQTVoiS/cJEDWMSw2rwE5p+z4jHTKNRLnRLjqQ
        v9i/dBksojC/nJDhKNJcAAAAEWl2YW5AaWFtbGFicDEubGFiAQIDBA==
        -----END OPENSSH PRIVATE KEY-----
...
