---
controller_credentials:
  - name: "Satellite"
    description: ""
    credential_type: "Red Hat Satellite 6"
    organization: "Satellite Register"
    inputs:
      host: https://satellite.bcnconsulting.com/
      password: ''
      username: admin

...
