---
controller_credentials:
  - name: "Satellite Register - Satellite"
    description: ""
    credential_type: "Satellite Register - Satellite Custom"
    organization: "Satellite Register"
    inputs:
      hostname: satellite.bcnconsulting.com
      password: ''
      username: admin

...
